### ISSUE TITLE
The very first interval is wrong.

### ISSUE THREAD

**Issue by KStandiford** [Blimp01/pico_non_blocking_timer#2]
First, thanks for this! It really showed how systick works. When I tried something similar, I found that the very first interval was wrong, and it was counting down from FFFFFF, not the value in the rvr register. Carefully reading the ARM documentation (which is a little fuzzy!), the rvr register is the RELOAD register. You need to clear the cvr (current count) by writing to it in order to force the rvr to be loaded initially.

So this code works.

    void init_systick()
    { 
        systick_hw->csr = 0; 	//Disable 
        systick_hw->rvr = 124999UL; //Standard System clock (125Mhz)/ (rvr value + 1) = 1ms 
        systick_hw->cvr = 0;        //clear the count to force initial reload
        systick_hw->csr = 0x7;      //Enable Systic, Enable Exceptions	
    }

Cheers!

**Comment by Blimp01** [comment]
Hello,

Added the fix thanks for the feedback :), Hope your project is going well!

all the best

Blimp!

**Comment by KStandiford** [comment]
You’re welcome! Worth it if I save somebody else the few hours of confusion it took me to figure it out. I’m getting ready to try to add preemptive scheduling to Gary’s Piccolo OS.  We’ll see …
.
